### ISSUE TITLE
Broken URLS

### ISSUE THREAD

**Issue by GodModed** [myfreeweb/awesome-gtk#158]
These URLS are broken:
* https://vocalproject.net/https://github.com/needle-and-thread/vocal
* https://gkarsay.github.io/parlatype
* https://github.com/misterdanb/shady/blob/master/Shadertoy.com
* https://www.gimp.or/
* https://youtube-dl.org
* http://parnold-x.github.io/nasc
* https://random.amongtech.cc
* https://useplanner.com
* http://guake-project.org
* https://github.com/fkinoshita/Wildcard
* https://gitlab.com/schmiddi-on-mobile/railwayde

**Comment by loicreynier** [comment]
Thanks! Closed with #157 and #159.
