### ISSUE TITLE
Add "Papers"

### ISSUE THREAD

**Issue by GerryT11** [myfreeweb/awesome-gtk#179]
Papers, a fork of Evince and designated successor in future Gnome versions is still missing in the list:
https://gitlab.gnome.org/GNOME/Incubator/papers
It is a GTK 4 and Libadwaita application.

Some further information is here:
https://thisweek.gnome.org/posts/2024/02/twig-136/
"Papers has been accepted into the GNOME Incubator. The GNOME incubation process is for apps that are designated to be accepted into GNOME Core or GNOME Development Tools if they reach the required maturity.

Papers is a fork of GNOME’s current document viewer Evince. Due to limited resources, the Evince project can currently not facilitate larger changes like the port to GTK 4 and Libadwaita. Those goals will now be pursued as part of the Papers project."

**Comment by loicreynier** [comment]
Thanks, closed with #180.
