### ISSUE TITLE
HandBrake is missing

### ISSUE THREAD

**Issue by GerryT11** [myfreeweb/awesome-gtk#184]
HandBrake 

HandBrake, open-source and cross-platform video transcoder application. GTK4

https://9to5linux.com/handbrake-1-8-video-transcoder-adds-gtk4-port-on-linux-ffmpeg-7-0-support
https://handbrake.fr/

**Comment by GerryT11** [comment]
Some additional info:
GTK4, but no libadwaita
https://www.omgubuntu.co.uk/2024/06/handbrake-completes-linux-gtk4-port

**Comment by loicreynier** [comment]
Closed with #208.
