### ISSUE TITLE
LibreOffice is missing

### ISSUE THREAD

**Issue by GerryT11** [myfreeweb/awesome-gtk#185]
LibreOffice (LibreOffice https://www.libreoffice.org/ is a free and powerful office suite) is missing in the list. 

LibreOffice uses native GTK3 widgets on Linux. GTK4 is in the works, but not yet there (https://wiki.documentfoundation.org/Development/GTK4). Internally, LibreOffice uses Visual Class Library (VCL), but it fully uses GTK3 for the UI.

P.S.: I've read issue 85 regarding Mozilla apps, but I think that LibreOffice is different, as it uses GTK3 native widgets.

**Comment by loicreynier** [comment]
Closed with #210.
