### ISSUE TITLE
Flowblade is missing

### ISSUE THREAD

**Issue by GerryT11** [myfreeweb/awesome-gtk#189]
Flowblade is a multitrack non-linear video editor for Linux released under GPL 3 license. Currently GTK3; GTK4 in development

With Flowblade Movie Editor you can compose movies from video clips, audio clips and graphics files. Clips can be cut at the desired frames, filters can be added to clips, and you can create multilayer composite images using compositor objects.

Flowblade github site : https://github.com/jliljebl/flowblade
Migrating from GTK 3.x to GTK 4 https://github.com/jliljebl/flowblade/blob/master/flowblade-trunk/docs/Migrating_from_GTK_3_to_GTK_4.md 

https://www.phoronix.com/news/Flowblade-2.16-Released Current release
https://www.phoronix.com/news/Flowblade-2.14-Released (with information that GTK4 will be ready in 2025)

**Comment by loicreynier** [comment]
Closed with #209.
