### ISSUE TITLE
Embellish

### ISSUE THREAD

**Issue by GerryT11** [myfreeweb/awesome-gtk#211]
Newly released this week (https://thisweek.gnome.org/posts/2024/07/twig-157/)

Embellish - Embellish, a simple nerd fonts manager

https://github.com/getnf/embellish?tab=readme-ov-file
User-friendly application designed for managing Nerd Fonts on your system. With a sleek GTK4 user interface enhanced by libadwaita, Embellish provides a seamless experience for installing, uninstalling and updating of Nerd Fonts. 

GTK4, Libadwaita, Go

**Comment by loicreynier** [comment]
Closed with #212.
