### ISSUE TITLE
Chats is missing

### ISSUE THREAD

**Issue by GerryT11** [myfreeweb/awesome-gtk#218]
Chats : Simple to use messaging application for mobile and desktop for 1:1 communication and small groups supporting SMS/MMS, Matrix and (optionally) XMPP.   #libadwaita #GTK4  (Programming language: Is it written in C?)

(As far as I understood, the application is called "Chats" and the project is called "Chatty")

https://gitlab.gnome.org/World/Chatty
https://flathub.org/apps/sm.puri.Chatty

**Comment by loicreynier** [comment]
Closed with #221.
