### ISSUE TITLE
Differentiate between GTK3 and GTK4

### ISSUE THREAD

**Issue by GerryT11** [myfreeweb/awesome-gtk#220]
Would it be possible to start adding information whether an application uses GTK3 or GKT4?
It would be helpful to just also have the hash tags #GTK3 and #GTK4.

I am requesting this, because I noticed that, by tendency, the GTK 4 applications are better maintained than those who still rely on the older GTK 3 (of course, bigger applications need more time to switch to GTK 4). GTK 4 applications also integrate better in recent Gnome versions.

**Comment by loicreynier** [comment]
99% of the time, GTK 4 applications are built using `libadwaita`. To distinguish between GTK 3 and GTK 4 applications, look for the `#libadwaita` tag.

Also, I believe the improved integration with GNOME is more likely due to the use of libadwaita rather than solely the GTK 4 implementation.

**Comment by GerryT11** [comment]
Thanks for your reply. It would be nice to see the differentiation between gtk3 and gtk4, but you are right that it might be not worth the effort. For me it would be rather an indicator which applications have already adopted / transitioned to GTK4.
Although  there is a large overlap between #GTK4 and #libadwaita, it is still not the same. Handbrake is GTK4, but not libadwaita. LibreOffice will, when the port to GTK4  will be finished, will also not support libadwaita. Gimp (when it will be GTK4) will also probably not support libadwaita (https://gitlab.gnome.org/GNOME/gimp/-/issues/6440). As far as I have seen, Inkscape GTK4 will also not support libadwaita.

**Comment by loicreynier** [comment]
You made a great point: several important applications have transitioned to GTK4 without relying on libadwaita. We could consider adding a :four: indicator at the end of the line for applications that have migrated to GTK4. For example:

- [HandBrake](https://handbrake.fr/) - Cross-platform video converter that supports nearly any format `#c` :four:.

This method of adding an image or emoji at the beginning or end of a line has been used in other awesome lists. However, I currently don't have the time to review and update the list for each application.

**Comment by GerryT11** [comment]
Thank you. That's a good idea! 

When I'll have time, I will also go through the list of applications and will post my findings (-> already migrated to GTK4, but not libadwaita) here in the bug report.

**Comment by loicreynier** [comment]
Instead of writing your findings in a issue, you could open a pull request and direclty edit the list. Here's the formatting you should use:

```markdown
- [HandBrake](https://handbrake.fr/) - Cross-platform video converter that supports nearly any format `#c` :four:.
```

**Comment by yvs2014** [comment]
> When I'll have time, I will also go through the list of applications and will post my findings (-> already migrated to GTK4, but not libadwaita) here in the bug report.

true, new GTK4 apps can still be used without libadwaita (at least in GNOME environment), I've used GTK4 not bound to a particular theming

**Comment by Drsheppard01** [comment]
I think resolve problem with my #230 PR
