### ISSUE TITLE
Bluefish is missing

### ISSUE THREAD

**Issue by GerryT11** [myfreeweb/awesome-gtk#225]
Bluefish - A powerful editor targeted towards programmers and web developers (C, JavaScript, Java, PHP, Python, as well as markup languages such as HTML, YAML and XML). 

#C 
GTK3

https://bluefish.openoffice.nl/
https://en.wikipedia.org/wiki/Bluefish_(software)

**Comment by GerryT11** [comment]
Created pull request: https://github.com/valpackett/awesome-gtk/pull/235

**Comment by loicreynier** [comment]
Closed with #235.
