### ISSUE TITLE
BMI calculator: Do you consider BMI as an actual application for the list?

### ISSUE THREAD

**Issue by GerryT11** [myfreeweb/awesome-gtk#239]
BMI  body mass index calculator: Do you consider BMI as an actual application suitable for the awesome list or is the app too simple?

Python, GTK4, LibAdwaita. 

https://github.com/PhilippKosarev/bmi

**Comment by loicreynier** [comment]
Sure we are already have applications such as Dippi that are as simple but yet useful.

Edit: I might add that simple applications are also a good resource for new developers and should not be neglected.
