### ISSUE TITLE
Mozilla apps

### ISSUE THREAD

**Issue by realmazharhussain** [myfreeweb/awesome-gtk#85]
Both Firefox and Thunderbird are missing from the list.

**Comment by loicreynier** [comment]
Firefox and Thunderbird are not GTK applications, they load a CSS theme that make it look and feels like a native GTK application.

**Comment by realmazharhussain** [comment]
Actually, what they do is the opposite. They use GTK3 to construct and present a window but they populate the window with web content instead of regular GTK widgets.

**Comment by loicreynier** [comment]
Thanks for the heads up. However, I believe that they use different toolkits depending on the platforms. In that veins they are more complex that just GTK applications. And since you cannot interact with them as regular GTK applications, I'm not sure it's relevant to reference them here.
